<?php
//Classes
include_once('classes/class.contact.php');
include_once('classes/class.person.php');
include_once('classes/class.staff.php');
include_once('classes/class.student.php');
include_once('classes/class.project.php');
include_once('classes/class.databaseconnection.php');
include_once('classes/class.projectcollection.php');
include_once('classes/class.studentcollection.php');
session_start();	
DatabaseConnection::get();
?>
